### ISSUE TITLE
I got an err when I Save Policy

### ISSUE THREAD

**Issue by HaoweiCh** [casbin/gorm-adapter#11]
```
(Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARSET=utf8' at line 1) 
[2019-03-29 21:53:15]  
panic: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CHARSET=utf8' at line 1

goroutine 1 [running]:
TongXingChuangYe/Spiders/vendor/github.com/casbin/gorm-adapter.(*Adapter).dropTable(...)
	/Users/c/go/src/TongXingChuangYe/Spiders/vendor/github.com/casbin/gorm-adapter/adapter.go:165
TongXingChuangYe/Spiders/vendor/github.com/casbin/gorm-adapter.(*Adapter).SavePolicy(0xc0002ae990, 0xc0002ae570, 0xc0002ae990, 0x0)
	/Users/c/go/src/TongXingChuangYe/Spiders/vendor/github.com/casbin/gorm-adapter/adapter.go:236 +0x756
TongXingChuangYe/Spiders/vendor/github.com/casbin/casbin.(*Enforcer).SavePolicy(0xc0003661c0, 0x4586d03, 0x1)
```

**Comment by hsluoyz** [comment]
Hi @HaoweiCh , it seems that Gorm's ``DropTable()`` fails to delete the table for MariaDB, maybe the SQL syntax is wrong for MariaDB. Can you provide a runnable example and your MariaDB version? So I can install the MariaDB and run your code to debug it.

https://github.com/casbin/gorm-adapter/blob/e74a050c51a4c12323e72f0c7ab445fb2daf6b40/adapter.go#L162-L167

**Comment by HaoweiCh** [comment]
```
func init() {
	DB = Connect(
		"39.106.169.37:3306",
		"bgx:bgx&@tcxy",
		"spiders",
	).Set("gorm:table_options", "CHARSET=utf8")
}

func Connect(hostAndPort, userNameAndPassword, databaseName string) (db *gorm.DB) {
	var err error
	if db, err = gorm.Open("mysql",
		fmt.Sprintf("%s@tcp(%s)/%s?charset=utf8mb4&collation=utf8mb4_unicode_ci&parseTime=true&loc=Local",
			userNameAndPassword, hostAndPort, databaseName)); err != nil {
		panic(err)
	}
	return
}
```

I guess `.Set("gorm:table_options", "CHARSET=utf8")` may cause this problem. but even remove it problem exists

`10.3.13-MariaDB`

if this info cannot help, I'll try provide more info.

**Comment by hsluoyz** [comment]
This is not an issue of this repo. You should ask in in Gorm's issue tracker.
