### ISSUE TITLE
[BUG] Error while creating enforcer if "gorm.io/gorm v1.21.3" present in go.mod

### ISSUE THREAD

**Issue by arafat-java** [casbin/gorm-adapter#98]
If the dependencies contain "gorm.io/gorm v1.21.3" then the following program gives error as follows

```go
package main

import (
	"fmt"
	"github.com/casbin/casbin/v2"
	pgAdapter "github.com/casbin/gorm-adapter/v3"
)

const DBHost = "SomeHost"
const DBUser = "SomeUser"
const DBName = "SomeDB"
const DBPassword = "SomePw"

func main() {

	dsn := fmt.Sprintf("host=%v port=5432 user=%v dbname=%v password=%v sslmode=allow", DBHost, DBUser, DBName, DBPassword)
	adapter1, _ := pgAdapter.NewFilteredAdapter("postgres", dsn, DBName, "casbin_rule_snowe", true)

	enforcer, _ := casbin.NewEnforcer()
	enforcer.InitWithAdapter("model.conf", adapter1)
}

```

**Error is as follows**
```
2021/04/23 09:22:11 C:/Users/sinarn/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.2.6/adapter.go:321 ERROR: relation "idx_casbin_rule_snowe" already exists (SQLSTATE 42P07)
[249.612ms] [rows:0] CREATE UNIQUE INDEX idx_casbin_rule_snowe ON casbin_rule_snowe (ptype,v0,v1,v2,v3,v4,v5)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x60 pc=0xe66285]

goroutine 1 [running]:
github.com/casbin/gorm-adapter/v3.(*Adapter).IsFiltered(0x0, 0xfe2960)
        C:/Users/sinarn/go/pkg/mod/github.com/casbin/gorm-adapter/v3@v3.2.6/adapter.go:396 +0x5
github.com/casbin/casbin/v2.(*Enforcer).InitWithModelAndAdapter(0xc000416580, 0xc000415080, 0xfe2960, 0x0, 0x0, 0xc000408948)
        C:/Users/sinarn/go/pkg/mod/github.com/casbin/casbin/v2@v2.25.6/enforcer.go:168 +0x144
github.com/casbin/casbin/v2.(*Enforcer).InitWithAdapter(0xc000416580, 0xf40b7d, 0xa, 0xfe2960, 0x0, 0x0, 0x3)
        C:/Users/sinarn/go/pkg/mod/github.com/casbin/casbin/v2@v2.25.6/enforcer.go:146 +0x85
main.main()
        C:/TNG/_GO/mkt-infra-iam/Source/main_jdbc_query_filtered_TEMP_gorm.go:20 +0x1eb
exit status 2
```

The moment "gorm.io/gorm v1.21.3" is removed from go.mod it starts working fine.
We need "gorm.io/gorm v1.21.3" for other modules in the system, so removing that is not an option for us

**Comment by hsluoyz** [comment]
@arafat-java can you try latest: https://github.com/casbin/gorm-adapter/releases/tag/v3.2.7 ?

**Comment by hsluoyz** [comment]
@closetool

**Comment by arafat-java** [comment]
> 
> 
> @arafat-java can you try latest: https://github.com/casbin/gorm-adapter/releases/tag/v3.2.7 ?

Getting the error with 3.2.7 as well

**Comment by closetool** [comment]
@hsluoyz @arafat-java That's not gorm-adapter's bug, gorm 1.21.x got many bugs, so we kept gorm-adapter's dependency at 1.20.x. Or you could try lastest version of gorm.

**Comment by hsluoyz** [comment]
Closed here. Please send bug report to: https://github.com/go-gorm/gorm

**Comment by arafat-java** [comment]
Thanks @hsluoyz Works fine with 1.20.x and as well with the latest 1.21.8
